#!/usr/bin/env bash
# Hand commits a freshly generated Homebrew formula to
# Kronaxis/homebrew-tap after a release tag has published its
# artifacts. Avoids needing HOMEBREW_TAP_TOKEN on the main repo.
#
# Usage:
#   scripts/publish-homebrew-formula.sh v0.3.0
#
# Requires:
#   - gh CLI authenticated with write access to Kronaxis/homebrew-tap
#   - the release at v<version> has finished and its checksums.txt is
#     downloadable
set -euo pipefail

VERSION="${1:-}"
if [[ -z "$VERSION" ]]; then
  echo "usage: $0 vX.Y.Z" >&2
  exit 2
fi
VERSION="${VERSION#v}"

CHECKSUMS_URL="https://github.com/Kronaxis/kronaxis-router/releases/download/v${VERSION}/checksums.txt"
echo "Fetching $CHECKSUMS_URL"

SUMS=$(curl -fsSL "$CHECKSUMS_URL")
get_sha() {
  echo "$SUMS" | awk -v want="kronaxis-router_${VERSION}_$1" '$2 == want { print $1; exit }'
}

DARWIN_AMD64=$(get_sha "darwin_amd64.tar.gz")
DARWIN_ARM64=$(get_sha "darwin_arm64.tar.gz")
LINUX_AMD64=$(get_sha "linux_amd64.tar.gz")
LINUX_ARM64=$(get_sha "linux_arm64.tar.gz")

for v in "$DARWIN_AMD64" "$DARWIN_ARM64" "$LINUX_AMD64" "$LINUX_ARM64"; do
  if [[ -z "$v" ]]; then
    echo "ERROR: missing one or more checksums for v${VERSION}" >&2
    echo "$SUMS"
    exit 1
  fi
done

FORMULA=$(mktemp)
cat > "$FORMULA" <<EOF
# typed: false
# frozen_string_literal: true

# This file is auto generated by scripts/publish-homebrew-formula.sh
# in Kronaxis/kronaxis-router. Do not edit by hand; rerun the script
# against a new release tag instead.
class KronaxisRouter < Formula
  desc "Tier routing LLM proxy for sovereign + frontier models"
  homepage "https://github.com/Kronaxis/kronaxis-router"
  version "${VERSION}"
  license "BUSL-1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Kronaxis/kronaxis-router/releases/download/v${VERSION}/kronaxis-router_${VERSION}_darwin_amd64.tar.gz"
      sha256 "${DARWIN_AMD64}"
      def install
        bin.install "kronaxis-router"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Kronaxis/kronaxis-router/releases/download/v${VERSION}/kronaxis-router_${VERSION}_darwin_arm64.tar.gz"
      sha256 "${DARWIN_ARM64}"
      def install
        bin.install "kronaxis-router"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Kronaxis/kronaxis-router/releases/download/v${VERSION}/kronaxis-router_${VERSION}_linux_amd64.tar.gz"
      sha256 "${LINUX_AMD64}"
      def install
        bin.install "kronaxis-router"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Kronaxis/kronaxis-router/releases/download/v${VERSION}/kronaxis-router_${VERSION}_linux_arm64.tar.gz"
      sha256 "${LINUX_ARM64}"
      def install
        bin.install "kronaxis-router"
      end
    end
  end

  test do
    system "#{bin}/kronaxis-router", "version"
  end
end
EOF

# Look up current SHA of the existing file (if any) so PUT can update.
EXISTING_SHA=$(gh api "repos/Kronaxis/homebrew-tap/contents/Formula/kronaxis-router.rb" --jq '.sha' 2>/dev/null || true)

B64=$(base64 -w0 "$FORMULA")
echo "Committing Formula/kronaxis-router.rb at v${VERSION}"
if [[ -n "$EXISTING_SHA" ]]; then
  gh api -X PUT "repos/Kronaxis/homebrew-tap/contents/Formula/kronaxis-router.rb" \
    -f message="kronaxis-router v${VERSION}" \
    -f content="$B64" \
    -f sha="$EXISTING_SHA" > /dev/null
else
  gh api -X PUT "repos/Kronaxis/homebrew-tap/contents/Formula/kronaxis-router.rb" \
    -f message="kronaxis-router v${VERSION}" \
    -f content="$B64" > /dev/null
fi
echo "done"
